# .github/workflows/auto-publish.yml

# Workflow name
name: 'Auto publish'

# Event for the workflow
on:
  pull_request:
    types:
      - closed

# List of jobs
jobs:
  build:
    runs-on: ubuntu-latest
    name: Running Publish Build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Publish to Chromatic
        run: npm run chromatic --project-token=CHROMATIC_PROJECT_TOKEN