# .github/workflows/auto-publish.yml

# Workflow name
name: 'Auto publish'

# Event for the workflow
on:
  pull_request:
    types:
      - closed

# List of jobs
jobs:
  chromatic-deployment:
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
        - name: Install dependencies
          # 👇 Install dependencies with the same package manager used in the project (replace it as needed), e.g. yarn, npm, pnpm
          run: yarn
          # 👇 Adds Chromatic as a step in the workflow
        - name: Branch
          run: echo The PR was merged to ${GITHUB_REF#refs/heads/}
        - name: Directory
          run: echo Run on directory ${GITHUB_WORKSPACE}
        - name: Publish to Chromatic
          run: npm run chromatic --project-token=CHROMATIC_PROJECT_TOKEN