# .github/workflows/auto-publish.yml

# Workflow name
name: 'Auto publish'

# Event for the workflow
on:
  pull_request:
    types:
      - closed

# List of jobs
jobs:
  chromatic-deployment:
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
        - name: Install dependencies
          run: npm install
        - name: Testing
          run: npm test
        - name: Publish to Chromatic
          uses: chromaui/action@v1
          run: npm run chromatic --project-token=CHROMATIC_PROJECT_TOKEN